---
title: "Communicating between R and WebVR sessions"
author: "Miles McBain"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## WebVR Side
The scene needs to have a web socket and some associated handler functions. 


```
```
Ideally the onmessage handler would route the message to an entity based on id, or the top level scene.

## R Side

```{r}
library(r2vr)

sources <- a_entity(js_sources = c("https://unpkg.com/aframe-event-set-component@^4.0.0/dist/aframe-event-set-component.min.js") )

box <- a_entity("box", id = "block",
                position = c(0, 1, -4),
                material = list(color = "red"),
                event_set__1 = list(`_event` = "switch_colour", material.color = "blue"),
                event_set__2 = list(`_event` = "rotate", rotation = c(0, 45, 0)))

my_scene <- a_scene(template = "basic",
                    children = list(box, sources),
                    websocket = TRUE)

my_scene$serve()

test_event <- list(a_event(id = "block",
                           event_name = "switch_colour",
                           event_detail = "any",
                           bubbles = FALSE),
                   a_event(id = "block",
                           event_name = "rotate",
                           event_detail = "any",
                           bubbles = FALSE)
                   )

my_scene$send_messages(test_event)

test_update <- list(a_update(id = "block",
                             component = "position",
                             attributes = list(x = 0, y = 0, z = -4)),
                    a_update(id = "block",
                             component = "color",
                             attributes = "green"))

my_scene$send_messages(test_update)

#try adding own handlers
my_scene$attach_ws_msg_hook(function(message, id){
  print(id)
  print(message)
})

a_kill_all_scenes()

```


